server:
  servlet:
    context-path: /salary-survey
  port: 8081
  
spring:
  logging:
    level: trace
  jpa:
    hibernate:
      ddl-auto: none
      format-sql: true
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
