#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true

server:
  servlet:
    context-path: /salary-survey

spring:
  logging:
    level: info
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://localhost:3306/fullstack
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver